title:              Bad Cloud Shape
email:              Jasont.davis1983@gmail.com
description:        Passion meets projects - showing my love of video games and the Cloud
author:             Jason Davis
baseurl:            "/badcloudshape.github.io"
url:                "https://badcloudshape.github.io/"

# Social Profiles
twitter_username:   Silentbob923
github_username:    badcloudshape
facebook_username:  StartBootstrap
linkedin_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
